import turtle as ss

class Main:
    def __init__(self) -> None:
        ss.speed(5)
        ss.color('cyan')
        ss.bgcolor('black')
        ## Square
        ss.forward(285)
        ss.right(90)
        ss.forward(285)
        ss.right(90)
        ss.forward(285)
        ss.right(90)
        ss.forward(285)
        ## Roof
        ss.right(45)
        ss.forward(200)
        ss.right(90)
        ss.forward(200)
        # Window right
        ss.right(45)
        ss.forward(50)
        ss.right(90)
        ss.forward(50)
        ss.right(90)
        ss.forward(50)
        # Distance Between Windows
        ss.left(90)
        ss.forward(183)
        # Window left
        ss.left(90)
        ss.forward(50)
        ss.right(90)
        ss.forward(50)
        # Distance Between Door and Windows
        ss.left(90)
        ss.forward(236)
        ss.left(90)
        ss.forward(100)
        # Door
        ss.left(90)
        ss.forward(100)
        ss.right(90)
        ss.forward(70)
        ss.right(90)
        ss.forward(100)
        # Enviorement
        ss.right(90)
        ss.forward(800)
        # Human
        ss.right(180)
        ss.forward(500)
        ss.left(45)
        ss.forward(50)
        ss.right(90)
        ss.forward(50)
        ss.left(180)
        ss.forward(50)
        ss.right(45)
        ss.forward(70)
        ss.left(135)
        ss.forward(50)
        ss.right(180)
        ss.forward(50)
        ss.right(90)
        ss.forward(50)
        ss.left(180)
        ss.forward(50)
        ss.right(45)
        ss.forward(30)
        ss.right(90)
        ss.circle(radius=30)
        ss.right(90)
        ss.forward(100)
        ss.right(45)
        ss.forward(50)
        # Distance Between Human And Well
        ss.right(45)
        ss.forward(100)
        # The Well
        ss.right(90)
        ss.forward(60)
        ss.left(90)
        ss.forward(150)
        ss.left(90)
        ss.forward(60)
        ss.left(90)
        ss.forward(150)
        ss.left(90)
        ss.forward(300)
        ss.left(90)
        ss.forward(150)
        ss.left(90)
        ss.forward(300)
        ss.right(180)
        ss.forward(300)
        ss.right(90)
        ss.forward(75)
        ss.right(90)
        ss.forward(20)
        ss.right(90)
        ss.forward(20)
        ss.right(90)
        ss.forward(20)
        ss.right(90)
        ss.forward(40)
        ss.right(90)
        ss.forward(20)
        ss.right(90)
        ss.forward(20)
        ss.left(90)
        ss.forward(60)
        # The Well's Bucket
        ss.right(90)
        ss.circle(radius=30, extent=90)
        ss.circle(radius=30, extent=-180)
        ss.left(90)
        ss.forward(59)
        ss.left(90)
        ss.forward(70)
        ss.left(90)
        ss.forward(59)
        ss.left(90)
        ss.forward(70)
        # Back To The Ground
        ss.circle(radius=30, extent=90)
        ss.right(90)
        ss.forward(80)
        ss.left(90)
        ss.forward(75)
        ss.left(90)
        ss.forward(300)
        # Go To Sky Point
        ss.right(90)
        ss.forward(250)
        ss.right(90)
        ss.forward(600)
        # The Sky
        ss.right(90)
        ss.forward(1200)
        ss.right(90)
        ss.forward(600)
        ss.right(90)
        ss.forward(400)
        
if __name__ == "__main__":
    import time as tt
    RUN = Main()
    tt.sleep(100)